### ISSUE TITLE
Service retired (auto-redirect) page

### ISSUE THREAD

**Issue by armstrongb** [ONSdigital/sdc-status-pages#1]
Add the service retired page to the repository. First deployed for the RM Closedown.

**Comment by armstrongb** [comment]
Can you amend the README to link to the appropriate template in the repo if you think it is useful or specify the filename so that users can identify the correct item at a later date?

**Comment by nicprice** [comment]
Just uploaded the html file exactly as used for the redirect on survey.ons.gov.uk from Friday
